
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ADD_LIKE_PRODUCTS = 'ADD_PRODUCTS'
export const ADD_PRODUCTS_TO_BASKET = 'ADD_PRODUCTS_TO_BASKET'
export const SHOW_LIKE_PRODUCTS = 'SHOW_LIKE_PRODUCTS'
export const SHOW_BASKET_PRODUCTS = 'SHOW_BASKET_PRODUCTS'
export const AUTHORIZATION = 'AUTHORIZATION'
export const LOG_OUT = 'LOG_OUT'

export const GET_DATA_FROM_SERVER = 'GET_DATA_FROM_SERVER'
